import type { Metadata } from "next";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import ThemeProviderWrapper from "@/components/ThemeProviderWrapper";
// import { ThemeProvider } from "next-themes"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AppLayout from "@/app/AppLayout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <ThemeProviderWrapper>
        <AppLayout>
        {children}
        </AppLayout>
      </ThemeProviderWrapper>
    </ClerkProvider>
  );
}
